<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/DeepLearningM10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
print(torch.__version__)

2.10.0+cpu


In [6]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Device name {torch.cuda.get_device_name(0)}")

else:
  print("GPU not abailable")

GPU not abailable


In [7]:
a = torch.empty(2,3)
a

tensor([[-9.3776e-37,  4.4371e-41, -9.3776e-37],
        [ 4.4371e-41,  0.0000e+00,  0.0000e+00]])

In [8]:
type(a)

torch.Tensor

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(2,3)

tensor([[0.7051, 0.6218, 0.3232],
        [0.7642, 0.2322, 0.4589]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
#identiti matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])