In [5]:
import torch
print(torch.__version__)

2.10.0+cpu


In [6]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Device name {torch.cuda.get_device_name(0)}")

else:
  print("GPU not abailable")

GPU not abailable


In [7]:
a = torch.empty(2,3)
a

tensor([[-9.3776e-37,  4.4371e-41, -9.3776e-37],
        [ 4.4371e-41,  0.0000e+00,  0.0000e+00]])

In [8]:
type(a)

torch.Tensor

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(2,3)

tensor([[0.7051, 0.6218, 0.3232],
        [0.7642, 0.2322, 0.4589]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
#identiti matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
X = torch.tensor([[1,2,3],[4,5,6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
X.shape

torch.Size([2, 3])

In [33]:
torch.empty_like(X)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6066683143735225654, 3977586904655343666, 6500437203900183086]])

In [34]:
torch.ones_like(X)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [35]:
torch.zeros_like(X)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [41]:
torch.rand_like(X,dtype=torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [42]:
torch.randint_like(X, low=0, high=10)

tensor([[0, 1, 9],
        [9, 8, 0]])

## Backwordpropogation

In [44]:
import torch
data = torch.tensor(
    [
        [2,3,3],
        [5,6,4],
        [7,8,5]
    ]
)

In [45]:
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [47]:
x = data[:,0:2]

In [49]:
x

tensor([[2, 3],
        [5, 6],
        [7, 8]])

In [46]:
y = data[:,2]

In [48]:
y

tensor([3, 4, 5])

In [50]:
def in_para():
  para = {}

  para['w1'] = torch.ones((2,2))*0.1
  para['b1'] = torch.zeros((2,1))

  para['w2'] = torch.ones((2,1))*0.1
  para['b2'] = torch.zeros((1,1))

  return para

In [51]:
in_para()

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

# Batter way

In [9]:
import torch
def batter_way(layer_dims):
   torch.manual_seed(3)
   parameters={}
   L = len(layer_dims)


   for l in range(1,L):
    parameters["w"+str(l)]= torch.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters["b"+str(l)]= torch.zeros((layer_dims[l],1))

   return parameters

In [13]:
batter_way([2,2,1])

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}