<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/ReadyDLtraindatasetM_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [185]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [186]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [187]:
df.shape

(569, 33)

In [188]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [189]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


# Train test split

In [190]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [191]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [192]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [193]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [194]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [195]:
len(df.columns)

31

In [196]:
len(X_train) + len(X_test)

569

In [197]:
X_train

array([[-0.14295036,  0.9512839 , -0.19522449, ..., -0.66044408,
        -0.43149984, -0.83063456],
       [-1.81050134,  1.48472625, -1.80507536, ..., -1.748837  ,
         0.24008088,  0.88627263],
       [-0.38355778,  0.77189621, -0.41980711, ..., -0.33319797,
        -0.12961139, -0.18988595],
       ...,
       [ 1.09971621,  0.32106662,  1.08616917, ...,  0.51017759,
         0.55165559, -0.44411475],
       [ 0.94402906,  4.73966872,  0.88088342, ...,  1.3855647 ,
        -0.09086635,  0.05686554],
       [-1.15350154, -0.39412379, -1.13050638, ..., -0.76285072,
        -0.0246769 , -0.4216828 ]])

In [198]:
y_train

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,

In [199]:
X_train

array([[-0.14295036,  0.9512839 , -0.19522449, ..., -0.66044408,
        -0.43149984, -0.83063456],
       [-1.81050134,  1.48472625, -1.80507536, ..., -1.748837  ,
         0.24008088,  0.88627263],
       [-0.38355778,  0.77189621, -0.41980711, ..., -0.33319797,
        -0.12961139, -0.18988595],
       ...,
       [ 1.09971621,  0.32106662,  1.08616917, ...,  0.51017759,
         0.55165559, -0.44411475],
       [ 0.94402906,  4.73966872,  0.88088342, ...,  1.3855647 ,
        -0.09086635,  0.05686554],
       [-1.15350154, -0.39412379, -1.13050638, ..., -0.76285072,
        -0.0246769 , -0.4216828 ]])

In [200]:
type(y_train)

numpy.ndarray

In [201]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [202]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_326/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_326/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_326/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_326/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommend

In [203]:
type(X_train_tensor)

torch.Tensor

In [204]:
from torch.utils.data import Dataset,DataLoader

In [205]:
class CustomDataset(Dataset):
  def __init__( self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [206]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [207]:
len(train_dataset)

455

In [208]:
X_train.shape[1]

30

In [213]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

In [209]:
import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


In [210]:
learning_rate = 0.1
loss_function = nn.BCELoss()

In [222]:
model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
epochs = 25
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:
    y_pred = model(batch_features)

    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


    print(f" {epoch+1} , Loss = {loss.item()} ")


 1 , Loss = 0.8022741079330444 
 1 , Loss = 0.5646674633026123 
 1 , Loss = 0.46786588430404663 
 1 , Loss = 0.41602057218551636 
 1 , Loss = 0.318813294172287 
 1 , Loss = 0.272413969039917 
 1 , Loss = 0.2495589405298233 
 1 , Loss = 0.2920920252799988 
 1 , Loss = 0.289002001285553 
 1 , Loss = 0.26928457617759705 
 1 , Loss = 0.3222716450691223 
 1 , Loss = 0.21692180633544922 
 1 , Loss = 0.23653657734394073 
 1 , Loss = 0.2816590964794159 
 1 , Loss = 0.17089061439037323 
 2 , Loss = 0.1730939745903015 
 2 , Loss = 0.30019599199295044 
 2 , Loss = 0.2026975452899933 
 2 , Loss = 0.1645914912223816 
 2 , Loss = 0.15881367027759552 
 2 , Loss = 0.17005763947963715 
 2 , Loss = 0.20462529361248016 
 2 , Loss = 0.19831962883472443 
 2 , Loss = 0.23423565924167633 
 2 , Loss = 0.15920527279376984 
 2 , Loss = 0.15673856437206268 
 2 , Loss = 0.18484865128993988 
 2 , Loss = 0.12094741314649582 
 2 , Loss = 0.12568719685077667 
 2 , Loss = 0.09967745840549469 
 3 , Loss = 0.14194652438

In [226]:
#model = MySimpleNN(X_train_tensor.shape[1])
#optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
#define loop
#batch_size = 32
#epochs = 25
#n_sample = len(X_train_tensor)
#for epoch in range(epochs):
  # for start_index in range(0,n_sample,batch_size):
 #   end_index = start_index + batch_size
   # print(f"Start index {start_index} end index{end_index}")
#    X_batch = X_train_tensor[start_index:end_index]
#    y_batch = y_train_tensor[start_index:end_index]

    #forward pass
 #   y_pred = model(X_batch)

 #   loss = loss_function(y_pred,y_batch.reshape(-1,1))


    #update step
 #   optimizer.zero_grad()
  #  loss.backward()
  #  optimizer.step()



#print step

 #  print(f" {epoch+1} , Loss = {loss.item()} ")




In [230]:
# model evalution
#model.eval()
#with torch.no_grad():
 # y_pred = model(X_test_tensor)
#  y_pred = (y_pred > 0.5).float()
 # accuracy = (y_pred.view(-1) == y_test_tensor).float().mean().item()
 # print(f"Test Accuracy = {accuracy}")

In [231]:
# model evalution
#model.eval()
#with torch.no_grad():
#  y_pred = model(X_train_tensor)
 # y_pred = (y_pred > 0.5).float()
#  accuracy = (y_pred.view(-1) == y_train_tensor).float().mean().item()
 # print(f"Accuracy = {accuracy}")

In [232]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)


0.9765625
